# Generated by Django 5.2.8 on 2025-11-24 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_rename_assigned_to_task_assignee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reviewers',
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
